// apps/site/src/lib/theme/ThemeToggle.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { Moon, Sun } from "@lucide/svelte";
  import {
    createThemeModeController,
    fallbackTranslate,
  } from "svedocs/theme/headless";
  import type { SvedocsThemeToggleProps } from "svedocs/theme/types";

  export let context: SvedocsThemeToggleProps["context"];
  const controller = createThemeModeController("system");
  let mode: "light" | "dark" = "light";
  $: t = context?.t ?? fallbackTranslate;
  $: label = t("theme.switch", {
    mode: t(mode === "dark" ? "theme.light" : "theme.dark"),
  });

  onMount(() => {
    const unsubscribe = controller.mode.subscribe((value) => (mode = value));
    const unmount = controller.mount();
    return () => {
      unsubscribe();
      unmount();
    };
  });
</script>

<button
  class="of-icon-button"
  type="button"
  aria-label={label}
  title={label}
  onclick={controller.toggle}
>
  {#if mode === "dark"}<Sun size={17} strokeWidth={1.8} />{:else}<Moon
      size={17}
      strokeWidth={1.8}
    />{/if}
</button>

// src/components/admin/shell/theme-toggle.tsx
"use client";

import { useTheme } from "@/components/ui/theme-provider";
import { useEffect, useState } from "react";
import { Moon, Sun } from "lucide-react";
import { Button } from "@/components/ui/button";

export function ThemeToggle() {
  const { resolvedTheme, setTheme } = useTheme();
  const [mounted, setMounted] = useState(false);
  useEffect(() => setMounted(true), []);

  if (!mounted) {
    return <Button variant="ghost" size="icon" className="size-8" aria-hidden />;
  }

  return (
    <Button
      variant="ghost"
      size="icon"
      className="size-8"
      onClick={() => setTheme(resolvedTheme === "dark" ? "light" : "dark")}
      aria-label="Toggle theme"
    >
      {resolvedTheme === "dark" ? (
        <Sun className="size-4" />
      ) : (
        <Moon className="size-4" />
      )}
    </Button>
  );
}
